In [1]:
import numpy as np

In [2]:
row=int(input("enter the no of rows:"))

enter the no of rows: 3


In [3]:
mat1=np.empty((row,row),dtype="int")
print("enter the matrix elements:")
for i in range(0,row):
    for j in range(0,row):
        mat1[i,j]=int(input())


enter the matrix elements:


 1
 2
 3
 4
 5
 6
 7
 8
 9


In [4]:
mat2=np.empty((row,row),dtype="int")
print("enter the matrix elements:")
for i in range(0,row):
    for j in range(0,row):
        mat2[i,j]=int(input())

enter the matrix elements:


 3
 0
 1
 2
 3
 4
 5
 6
 7


In [5]:
print(mat1)
print(mat2)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[3 0 1]
 [2 3 4]
 [5 6 7]]


In [6]:
dot=np.dot(mat1,mat2)
print(dot)


[[ 22  24  30]
 [ 52  51  66]
 [ 82  78 102]]


In [7]:
tr=np.transpose(mat1)
print(tr)

[[1 4 7]
 [2 5 8]
 [3 6 9]]


In [8]:
trace=np.trace(mat1)
print(trace)

15


In [9]:
r=np.linalg.matrix_rank(mat1)
print(r)

2


In [10]:
det=np.linalg.det(mat2)
print(det)

-11.999999999999995


In [11]:
inverse=np.linalg.inv(mat2)
print(inverse)

[[ 0.25       -0.5         0.25      ]
 [-0.5        -1.33333333  0.83333333]
 [ 0.25        1.5        -0.75      ]]


In [12]:
eigv,eigvec=np.linalg.eig(mat1)
print("eigen values:",eigv)
print("eigenvectors:",eigvec)

eigen values: [ 1.61168440e+01 -1.11684397e+00 -1.30367773e-15]
eigenvectors: [[-0.23197069 -0.78583024  0.40824829]
 [-0.52532209 -0.08675134 -0.81649658]
 [-0.8186735   0.61232756  0.40824829]]
