In [ ]:
QN1

In [32]:
import numpy as np
x=([1,2,3,4,5])
y=([1,3,4,6,7])

In [20]:
print(x)
print(y)

[1 2 3 4 5]
[1 3 4 6 7]


In [21]:
print(np.greater(x,y))

[False False False False False]


In [22]:
print(np.greater(y,x))

[False  True  True  True  True]


In [23]:
print(np.less(x,y))

[False  True  True  True  True]


In [24]:
print(np.greater(y,x))

[False  True  True  True  True]


In [25]:
print(np.less(y,x))

[False False False False False]


In [26]:
print(np.equal(x,y))

[ True False False False False]


In [27]:
print(np.not_equal(x,y))

[False  True  True  True  True]


In [ ]:
QN2

In [29]:
print(np.arange(30,71,2))

[30 32 34 36 38 40 42 44 46 48 50 52 54 56 58 60 62 64 66 68]


In [ ]:
QN3

In [30]:
a=np.identity(3)

In [31]:
print("3*3 matrix")
c

3*3 matrix
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [32]:
a=np.identity(2)
print(a)

[[1. 0.]
 [0. 1.]]


In [ ]:
QN4

In [35]:
s=np.arange(0,21,1)
print("originalvector")
print(s)

originalvector
[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20]


In [42]:
print("After changing")
s[(s>=8)& (s<=15)]*=-1
print(s)

After changing
[  0   1   2   3   4   5   6   7  -8  -9 -10 -11 -12 -13 -14 -15  16  17
  18  19  20]


In [ ]:
QN5

In [43]:
d=np.diag([1,2,3,4,5])
print(d)

[[1 0 0 0 0]
 [0 2 0 0 0]
 [0 0 3 0 0]
 [0 0 0 4 0]
 [0 0 0 0 5]]


In [ ]:
QN6

In [11]:
a=np.array([[4,2],[1,2]])
print("original array")
print(a)
print("Sum of all elements")
print(np.sum(a))
print("sum of each column")
print(np.sum(a,axis=0))
print("sum of each row")
print(np.sum(a,axis=1))

original array
[[4 2]
 [1 2]]
Sum of all elements
9
sum of each column
[5 4]
sum of each row
[6 3]


In [ ]:
QN7

In [19]:
import os
x=np.arange(12).reshape(4,3)
print("original")
print(x)
header='col1 col2 col3'
np.savetxt('temp.txt',x,fmt="%d",header=header)
print("After loading,content of the file")
result=np.loadtxt('temp.txt')
print(result)

original
[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]
After loading,content of the file
[[ 0.  1.  2.]
 [ 3.  4.  5.]
 [ 6.  7.  8.]
 [ 9. 10. 11.]]


In [ ]:
QN8

In [23]:
x=np.array([1,2,3,4,5])
y=np.array([1,2,4,6,5])
print(np.equal(x,y))

[ True  True False False  True]


In [ ]:
QN9

In [28]:
nums=np.arange(16,dtype='int').reshape(-1,4)
print("original")
print(nums)
print("after swapping last and first....")
nums[[0,-1],:]=nums[[-1,0],:]
print(nums)


original
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]
after swapping last and first....
[[12 13 14 15]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [ 0  1  2  3]]


In [ ]:
QN10

In [29]:
a=np.array([[1,2,3],[2,3,4]])
b=np.array([[1,2,3],[2,3,4]])
c=a*b


[[ 1  4  9]
 [ 4  9 16]]
